// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       number[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:         string;
    type:       string;
    place_type: string[];
    relevance:  number;
    properties: Properties;
    text:       Text;
    place_name: string;
    center:     number[];
    geometry:   Geometry;
    context?:   Context[];
    bbox?:      number[];
}

export interface Context {
    id:          string;
    mapbox_id:   string;
    text:        Text;
    wikidata?:   string;
    short_code?: string;
}

export enum Text {
    Argentina = "Argentina",
    Córdoba = "Córdoba",
    PalacioFerreyra = "Palacio Ferreyra",
    X5000 = "X5000",
}

export interface Geometry {
    coordinates: number[];
    type:        string;
}

export interface Properties {
    foursquare?: string;
    landmark?:   boolean;
    wikidata?:   string;
    address?:    string;
    category?:   string;
    mapbox_id?:  string;
    short_code?: string;
}
